stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/rails/Dockerfile
      buildContext: .
      tag: blood-rail
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
