version: "3"

services:
  db:
    image: mysql:5.7.20
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    env_file: .env
    networks:
      - clbhieuvathuong_docker
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: docker/common/wait-for-it.sh db:3306 -- docker/app/entrypoint.sh
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - 3000:3000
    env_file: .env
    stdin_open: true
    tty: true
    networks:
      - clbhieuvathuong_docker
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - public-files:/nginx/public
      - log-nginx:/nginx/log
    networks:
      - git
volumes:
  db-data:
  bundle:
  log-nginx:
networks:
  clbhieuvathuong_docker:
    external:
      name: clbhieuvathuong_docker
