export const STATISTICS_FETCHED = 'STATISTICS_FETCHED'
export const GENDERS_FETCHED = 'GENDERS_FETCHED'
export const TOP_USERS_FETCHED = 'TOP_USERS_FETCHED'

export default {
  STATISTICS_FETCHED,
  GENDERS_FETCHED,
  TOP_USERS_FETCHED
}
