email_regex: !ruby/regexp /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
minimum_frequency:
  platelets: 2
  whole_blood: 3
default_frequency: 4
statuses:
  can_donate: can_donate
  almost: almost
  cannot_donate: cannot_donate
  unknown: unknown
radiuses:
  1km: 1
  2km: 2
  5km: 5
default_radius: 1
default_position:
  lat: 16.075588999999994
  lng: 108.15342699999997
admin_email: <%= ENV["ADMIN_EMAIL"] %>
cloudinary_default_path: "https://res.cloudinary.com/sontd/image/upload/"
avatar_cloudinary:
  file: "default_avatar_bmsdn.png"
  version: "v1494756572"
image_cloudinary:
  file: "default_article.png"
  version: "v1494760421"
common_blood_type_regex: !ruby/regexp /\A(ab|a|b|o)/
histories:
  search_items:
    donator: user_name_or_place_name_cont
    patient: patient_name_cont
  excel_attrs:
    - "display_user_name"
    - "display_user_birthday"
    - "display_user_gender"
    - "display_user_blood_type"
    - "display_donation_type_excel"
    - "place_name"
    - "user_facebook_account"
fb_search_path:
  people: "https://www.facebook.com/search/people/?q="
  home: "https://www.facebook.com"
blood_recipient_scheme:
  a_pos:
    - a_pos
    - a_neg
    - o_pos
    - o_neg
  a_neg:
    - a_neg
    - o_neg
  b_pos:
    - b_pos
    - b_neg
    - o_pos
    - o_neg
  b_neg:
    - b_neg
    - o_neg
  ab_pos:
    - a_pos
    - a_neg
    - b_pos
    - b_neg
    - ab_pos
    - ab_neg
    - o_pos
    - o_neg
  ab_neg:
    - a_neg
    - b_neg
    - ab_neg
    - o_neg
  o_pos:
    - o_pos
    - o_neg
  o_neg:
    - o_neg
blood_donor_scheme:
  a_pos:
    - a_pos
    - ab_pos
  a_neg:
    - a_pos
    - a_neg
    - ab_pos
    - ab_neg
  b_pos:
    - b_pos
    - ab_pos
  b_neg:
    - b_pos
    - b_neg
    - ab_pos
    - ab_neg
  ab_pos:
    - ab_pos
  ab_neg:
    - ab_pos
    - ab_neg
  o_pos:
    - a_pos
    - b_pos
    - ab_pos
    - o_pos
  o_neg:
    - a_pos
    - a_neg
    - b_pos
    - b_neg
    - ab_pos
    - ab_neg
    - o_pos
    - o_neg
allowed_weekly_data:
  - user
  - history
